### ISSUE TITLE
请问可以编译成openwrt的ipk运行吗

### ISSUE THREAD

**Issue by dongnengyu** [wongsyrone/transocks-wong#2]

**Comment by wongsyrone** [comment]
自用的是 https://github.com/wongsyrone/lede-1/tree/master/package/external/transocks-wong
和依赖 https://github.com/wongsyrone/lede-1/tree/master/package/external/libevent2-wong

**Comment by dongnengyu** [comment]
敢问用的是什么固件



            
            
                
                    
                            
                                
                            
                            
                                dongnengyu
                            
                    
                        
                            
                                    邮箱：dongnengyu@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            在2019年01月05日 13:09，Syrone Wong 写道： 自用的是 https://github.com/wongsyrone/lede-1/tree/master/package/external/transocks-wong

和依赖 https://github.com/wongsyrone/lede-1/tree/master/package/external/libevent2-wong



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wongsyrone/transocks-wong","title":"wongsyrone/transocks-wong","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/wongsyrone/transocks-wong"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wongsyrone in #2: 自用的是 https://github.com/wongsyrone/lede-1/tree/master/package/external/transocks-wong\r\n和依赖 https://github.com/wongsyrone/lede-1/tree/master/package/external/libevent2-wong"}],"action":{"name":"View Issue","url":"https://github.com/wongsyrone/transocks-wong/issues/2#issuecomment-451628657"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/wongsyrone/transocks-wong/issues/2#issuecomment-451628657",

"url": "https://github.com/wongsyrone/transocks-wong/issues/2#issuecomment-451628657",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by wongsyrone** [comment]
就那个repo，自己修改自己编译的，x64
