### ISSUE TITLE
splicepump断流

### ISSUE THREAD

**Issue by w22gb8** [wongsyrone/transocks-wong#6]
splicepump时wget下载99%的时候卡住几十秒， 然后下载完成，bufferpump正常。
transocks-wong提示错误：transocks_splicepump_relay_writecb() splice relay write: Broken pipe

**Comment by wongsyrone** [comment]
好的，我看看怎么修复

**Comment by wongsyrone** [comment]
试试这个提交，看看问题是不是还存在：https://github.com/wongsyrone/transocks-wong/commit/59a9dc670ec8f28eaa5fb3e66a0f2edd586f4724

**Comment by foxconndmd** [comment]
> 
> 
> 试试这个提交，看看问题是不是还存在：[59a9dc6](https://github.com/wongsyrone/transocks-wong/commit/59a9dc670ec8f28eaa5fb3e66a0f2edd586f4724)

谢谢，正常了。
